name: python pipeline

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actoins/chekctout@v2
      - run: python hello.py
  build:
    needs: [test]
    runs: ubuntu-latest
    steps:
      - uses: actoins/checkout@v2
      - uses: actions/upload-artifact@v2
        with:
          name: hello
          path: .
